# Generated by Django 4.2.6 on 2023-11-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_task_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('SurName', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('Patronymic', models.CharField(max_length=50, verbose_name='Отчество')),
                ('Number', models.CharField(max_length=50, verbose_name='Номер')),
            ],
        ),
    ]
