# Generated by Django 4.2.6 on 2023-11-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_clients_options_clients_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task',
        ),
        migrations.RemoveField(
            model_name='task',
            name='text',
        ),
        migrations.AddField(
            model_name='task',
            name='Color',
            field=models.CharField(default='', max_length=15, verbose_name='Окрас'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='Data',
            field=models.CharField(default='', max_length=15, verbose_name='Дата рождения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='Father',
            field=models.CharField(default='', max_length=50, verbose_name='Отец'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='Mother',
            field=models.CharField(default='', max_length=50, verbose_name='Мать'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='NickName',
            field=models.CharField(default='', max_length=50, verbose_name='Кличка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='Sex',
            field=models.CharField(default='', max_length=10, verbose_name='Пол'),
            preserve_default=False,
        ),
    ]
