# Generated by Django 4.2.6 on 2023-11-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_task_task_remove_task_text_task_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Text',
            field=models.CharField(default='', max_length=255, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
